# Copyright 2020-2021 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

# CI script for Github Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Use Khronos container with asciidoctor toolchain preinstalled
    container: khronosgroup/docker-images:vulkan-docs-base

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Verify REUSE compliance
        run: |
          reuse lint
